name: "autonomous_data_engineer"
version: "1.0.0"
config-version: 2

profile: "autonomous_data_engineer"

model-paths:
  - "models"

target-path: "target"

clean-targets:
  - "target"
  - "dbt_packages"

models:
  autonomous_data_engineer:
    +materialized: view

    staging:
      +schema: silver
      +materialized: view

    marts:
      +schema: gold
      +materialized: table