from typing import Annotated, Literal

from langchain_core.messages import AnyMessage
from langgraph.graph.message import add_messages
from pydantic import BaseModel, Field


class AgentSchema(BaseModel):
    messages: Annotated[
        list[AnyMessage],
        add_messages,
    ] = Field(
        default_factory=list
    )

    user_question: str = ""
    curated_ques: str = ""
    prompt_query: str = ""

    # Exact governed catalog snapshot used
    # for both prompting and validation.
    analytics_catalog: dict[
        str,
        object,
    ] = Field(
        default_factory=dict
    )

    is_safe: Literal[
        "YES",
        "NO",
    ] = "NO"

    generated_sql_query: str = ""
    comments: str = ""
    sql_query_execution_result: str = ""
    final_answer: str = ""

    run_id: str = ""

    referenced_relations: list[
        str
    ] = Field(
        default_factory=list
    )

    sql_execution_failed: bool = False


class JudgeSchema(BaseModel):
    answer: Literal["YES", "NO"]
    comments: str


class ETLAgentSchema(BaseModel):
    messages: Annotated[
        list[AnyMessage],
        add_messages,
    ] = Field(
        default_factory=list
    )

    run_id: str = ""

    tool_call_count: int = 0

    workflow_failed: bool = False

    failure_reason: str = ""


class RouterSchema(BaseModel):
    answer: Literal["sql", "etl"]
    comments: str = ""


class DataEngineerSchema(BaseModel):
    messages: Annotated[list[AnyMessage], add_messages] = Field(default_factory=list)

    route_response: Literal["sql", "etl"] | None = None


# ============================================================
# ETL TRANSFORMATION SCHEMAS
# ============================================================

class SelectColumnsOperation(BaseModel):
    type: Literal["select_columns"]
    columns: list[str]


class DropColumnsOperation(BaseModel):
    type: Literal["drop_columns"]
    columns: list[str]


class RenameColumnsOperation(BaseModel):
    type: Literal["rename_columns"]
    mapping: dict[str, str]


class FilterRowsOperation(BaseModel):
    type: Literal["filter_rows"]

    column: str

    operator: Literal[
        "eq",
        "ne",
        "gt",
        "gte",
        "lt",
        "lte",
        "contains",
        "in",
        "not_in",
        "is_null",
        "not_null",
    ]

    value: (
        str
        | int
        | float
        | bool
        | list[str]
        | list[int]
        | list[float]
        | list[bool]
        | None
    ) = None

    case_sensitive: bool = False


class DropDuplicatesOperation(BaseModel):
    type: Literal["drop_duplicates"]

    subset: list[str] | None = None

    keep: Literal[
        "first",
        "last",
    ] = "first"


class SortValuesOperation(BaseModel):
    type: Literal["sort_values"]

    columns: list[str]

    ascending: bool = True


class FillMissingOperation(BaseModel):
    type: Literal["fill_missing"]

    values: dict[
        str,
        str | int | float | bool
    ]


class CastColumnsOperation(BaseModel):
    type: Literal["cast_columns"]

    dtypes: dict[
        str,
        Literal[
            "string",
            "integer",
            "float",
            "boolean",
            "datetime",
            "category",
        ],
    ]


class StringTransformOperation(BaseModel):
    type: Literal["string_transform"]

    columns: list[str]

    action: Literal[
        "strip",
        "lower",
        "upper",
    ]


class AggregationSpec(BaseModel):
    column: str

    function: Literal[
        "sum",
        "mean",
        "min",
        "max",
        "count",
        "median",
        "nunique",
    ]

    alias: str


class GroupByAggregateOperation(BaseModel):
    type: Literal["groupby_aggregate"]

    group_by: list[str]

    aggregations: list[AggregationSpec]


TransformationOperation = Annotated[
    SelectColumnsOperation
    | DropColumnsOperation
    | RenameColumnsOperation
    | FilterRowsOperation
    | DropDuplicatesOperation
    | SortValuesOperation
    | FillMissingOperation
    | CastColumnsOperation
    | StringTransformOperation
    | GroupByAggregateOperation,
    Field(discriminator="type"),
]


class TransformPlan(BaseModel):
    """
    A validated ETL transformation plan generated by the LLM.

    The LLM chooses WHAT operations should happen.
    Python code in ETLTools controls HOW they happen.
    """

    operations: list[TransformationOperation] = Field(
        default_factory=list
    )

    summary: str = ""


DBTTransformationOperation = Annotated[
    (
        SelectColumnsOperation
        | RenameColumnsOperation
        | FilterRowsOperation
        | FillMissingOperation
        | CastColumnsOperation
        | StringTransformOperation
        | GroupByAggregateOperation
    ),
    Field(
        discriminator="type"
    ),
]


class DBTTransformPlan(BaseModel):
    """
    Structured transformation plan for dbt models.

    The LLM decides WHAT should happen.

    Deterministic Python compiles the plan into
    PostgreSQL/dbt SQL.

    Arbitrary SQL is never supplied by the LLM.
    """

    operations: list[
        DBTTransformationOperation
    ] = Field(
        default_factory=list
    )

    summary: str = ""